[metadata_configs]
[metadata_configs.torch]
normalize_package_name = false
normalize_version = true
deps_remove_list = [
  # XPU
  'dpcpp-cpp-rt',
  'impi-rt',
  'intel-cmplr-lib-rt',
  'intel-cmplr-lib-ur',
  'intel-cmplr-lic-rt',
  'intel-opencl-rt',
  'intel-openmp',
  'intel-pti',
  'intel-sycl-rt',
  'mkl',
  'oneccl-devel',
  'oneccl',
  'onemkl-sycl-blas',
  'onemkl-sycl-dft',
  'onemkl-sycl-lapack',
  'onemkl-sycl-rng',
  'onemkl-sycl-sparse',
  'pytorch-triton-xpu',
  'tbb',
  'tcmlib',
  'umf',
]
deps_add_list    = [
    # XPU
    'dpcpp-cpp-rt==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'impi-rt==2021.16.1; platform_system == "Linux" and platform_machine == "x86_64" and "intel" in variant_namespaces',
    'intel-cmplr-lib-rt==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'intel-cmplr-lib-ur==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'intel-cmplr-lic-rt==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'intel-opencl-rt==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'intel-openmp==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'intel-pti==0.13.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'intel-sycl-rt==2025.2.1; platform_system == "Linux" and "intel" in variant_namespaces',
    'mkl==2025.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'oneccl-devel==2021.16.1; platform_system == "Linux" and platform_machine == "x86_64" and "intel" in variant_namespaces',
    'oneccl==2021.16.1; platform_system == "Linux" and platform_machine == "x86_64" and "intel" in variant_namespaces',
    'onemkl-sycl-blas==2025.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'onemkl-sycl-dft==2025.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'onemkl-sycl-lapack==2025.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'onemkl-sycl-rng==2025.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'onemkl-sycl-sparse==2025.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'pytorch-triton-xpu==3.5.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'tbb==2022.2.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'tcmlib==1.4.0; platform_system == "Linux" and "intel" in variant_namespaces',
    'umf==0.11.0; platform_system == "Linux" and "intel" in variant_namespaces',
]

[metadata_configs.torchvision]
normalize_package_name = false
normalize_version = true
deps_remove_list = ["torch"]
deps_add_list    = ["torch==2.9.0"]

[variant_configs.intel]
variant_label = "xpu"  # [a-z0-9_]{1,8}
properties = [
  { namespace = "intel", feature = "device_ip", value = "20.4.4" },   # lnl-m
  { namespace = "intel", feature = "device_ip", value = "20.1.0" },   # bmg
  { namespace = "intel", feature = "device_ip", value = "12.74.4" },  # arl-h
  { namespace = "intel", feature = "device_ip", value = "12.71.4" },  # mtl-h
  { namespace = "intel", feature = "device_ip", value = "12.60.7" },  # pvc
  { namespace = "intel", feature = "device_ip", value = "12.55.8" },  # dg2
]

[variant_configs.cpu]
# variant_label = None  # FORBIDDEN - No Alias -> NULL VARIANT: `00000000`
properties = []
